// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdjHrDVNw5YoqgNCZuLd6gUXD8cSydS5M',
    appId: '1:369642936197:web:60026f56093226300c16ec',
    messagingSenderId: '369642936197',
    projectId: 'itshackathon-5aa3a',
    authDomain: 'itshackathon-5aa3a.firebaseapp.com',
    storageBucket: 'itshackathon-5aa3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8X05F3Y3CcnhNMaphET4C_1EjpcZ-D-U',
    appId: '1:369642936197:android:69f1e20271dc1caa0c16ec',
    messagingSenderId: '369642936197',
    projectId: 'itshackathon-5aa3a',
    storageBucket: 'itshackathon-5aa3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBweazW5gF9S-DCNG0sxEdChDDOI9rkHAc',
    appId: '1:369642936197:ios:5fb01bab4054066e0c16ec',
    messagingSenderId: '369642936197',
    projectId: 'itshackathon-5aa3a',
    storageBucket: 'itshackathon-5aa3a.appspot.com',
    androidClientId: '369642936197-p6k98p1fppubfu66e5o45t3b0k8qpacu.apps.googleusercontent.com',
    iosClientId: '369642936197-o9sv6lqiut05feki8oe19o0afs6ch55m.apps.googleusercontent.com',
    iosBundleId: 'com.example.codesageuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBweazW5gF9S-DCNG0sxEdChDDOI9rkHAc',
    appId: '1:369642936197:ios:5fb01bab4054066e0c16ec',
    messagingSenderId: '369642936197',
    projectId: 'itshackathon-5aa3a',
    storageBucket: 'itshackathon-5aa3a.appspot.com',
    androidClientId: '369642936197-p6k98p1fppubfu66e5o45t3b0k8qpacu.apps.googleusercontent.com',
    iosClientId: '369642936197-o9sv6lqiut05feki8oe19o0afs6ch55m.apps.googleusercontent.com',
    iosBundleId: 'com.example.codesageuser',
  );
}
